### ISSUE TITLE
No templates were found in the package

### ISSUE THREAD

**Issue by ALVSoft** [mehdihadeli/vertical-slice-api-template#6]
Hi @mehdihadeli 
I get this message "**No templates were found in the package**" when run this command `dotnet new install Vertical.Slice.Template`

Thanks

**Comment by mehdihadeli** [comment]
Hi,
Thanks for the report, I will fix this.

**Comment by mrashed** [comment]
still not fixed

**Comment by mehdihadeli** [comment]
Fixed in latest version `v1.3.3`

**Comment by scottpage** [comment]
Still seeing it in v1.3.4

**Comment by mehdihadeli** [comment]
Thanks for reporting, I check the issue.

**Comment by marcelocamargosjr** [comment]
![image](https://github.com/user-attachments/assets/99059b93-fe0e-41b1-a12c-c8062c68b8bd)

**Comment by scottpage** [comment]
Are you running your own releases in a test environment or just relying on the pipeline to build it and carrying on?

**Comment by mehdihadeli** [comment]
@scottpage 
Can you check this version?
`dotnet new install Vertical.Slice.Template::1.3.5`

**Comment by marcelocamargosjr** [comment]
@mehdihadeli It worked. It functioned perfectly.
